aimrt:
  plugin:
    plugins:
      - name: echo_plugin
        path: libaimrt_echo_plugin.so
        options:
          type_support_pkgs:
            - path: /opt/agibot/bin/libaimdk_protocol_joint_msgs_type_support.so
          topic_meta_list:
            - topic_name: /hal_debug/leg_joint_command
              msg_type: ros2:joint_msgs/msg/JointCommand
              echo_type: yaml
      - name: iceoryx_plugin
        path: libaimrt_iceoryx_plugin.so

  log:
    core_lvl: Info
    default_module_lvl: Info
    backends:
      - type: console

  executor:
    executors:
      - type: asio_thread
        name: echo_thread_pool
        options:
          thread_num: 2

  channel:
    backends:
      - type: iceoryx
    sub_topics_options:
      - topic_name: /hal_debug/leg_joint_command
        enable_backends: [iceoryx]

  main_thread:
    name: echo

  module:
    pkgs: []
    modules:
      - name: echo
